name: Deploy

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    branches:
      - main

env:
  # See: https://github.com/actions/setup-node/#readme
  NODE_VERSION: '18.17'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: 'https://registry.npmjs.org'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn
      - name: Test
        run: yarn test
      - name: Package
        run: yarn package

      - name: Upload VS Code Extension [GitHub Actions]
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: build-artifacts/

      - name: Upload VS Code Extension [S3]
        uses: docker://plugins/s3
        env:
          PLUGIN_SOURCE: 'build-artifacts/*'
          PLUGIN_STRIP_PREFIX: 'build-artifacts/'
          PLUGIN_TARGET: '/vscode-arduino-tools'
          PLUGIN_BUCKET: ${{ secrets.DOWNLOADS_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
